@startuml
class main{

'security
interface login {
function login_name
let name
function password
}

abstract class user {
}

class admin {
function <login> login
}

interface securiteit {

}
'users
class brouwer {
let name
let owner
function <adres> adres
function <selling_points> selling_points
function <brands> brands
}

class drinker {
let name
function brand-preferenc <brands>
function <adres> adres
function <selling_points> selling_points
function <brands> brands

}

class selling_points <list> {
function <adres> adres
}

class brands <array> {
const name
let name-beer
let type
let flavour
let color
let %
}
'data
abstract class adres {
let street
let city
let state
let country
let (district)

}

'links
user "1" <-D-> "1" brouwer
user "1" <-D-> "1" drinker
user "1" <-D-> "1" admin
login "*" <-D-> "N" user

securiteit "1" --> "N" brouwer
securiteit "1" --> "N" drinkergit
securiteit "1" --> "N" admin
securiteit "1" -R-> "N" user
securiteit "1" -U-> "N" login
securiteit "1" --> "N" selling_points

selling_points "1" <-u-> "N" brouwer
selling_points "1" -u-> "N" drinker
selling_points "1" <-u-> "N" admin
selling_points "1" -u-> "N" brands

brands "N" -U-> "0..1" brouwer
brands "N" -U-> "0..1" drinker
brands "N" <-U-> "0..1" admin

admin "1" -L-> "0.N" drinker
admin "1" -R-> "0.N" brouwer

adres "1" -U-> "1" brouwer
adres "1" -U-> "1" drinker
adres "1" --> "1" selling_points
adres "1" <-U- "N" securiteit



}
@enduml
