@startuml
class main{
abstract class user {
}
class admin {
function <login> login
}
interface securiteit {

}

class brouwer {
let name
let owner
function <adres> adres

}

class selling_points <list> {
function <adres> adres

}

class brands <array> {
const name
let name-beer
let type
let flavour
let color
let %
}
class drinker {
function <adres> adres
function brand-preferenc <brands>
}
abstract class adres <array> {
let street
let city
let country
let postcode
let district

}

interface login {
function login_name
function password
}



user "1" <-D- "1" brouwer
user "1" <-D- "1" drinker
user "1" <-D- "1" admin
login "*" <-D-> "n" user

securiteit "1" <--> "1" brouwer
securiteit "1" <--> "1" drinker
securiteit "1" <--> "1" admin
securiteit "*" <-R-> "n" user
securiteit "*" <-U-> "n" login
securiteit "*" <--> "n" selling_points

selling_points "1" <-u-> "N" brouwer
selling_points "1" <-u-> "N" drinker
selling_points "1" <-u-> "N" admin
selling_points "1" <-u-> "N" brands


brands "N" <-U-> "0..1" brouwer
brands "N" -U-> "0..1" drinker
brands "N" <-U-> "0..1" admin

admin "1" <-L-> "0..N" drinker
admin "1" <-R-> "0..N" brouwer

adres "1" <-U-> "1" brouwer
adres "1" <-U-> "1" drinker
adres "1" <--> "1" selling_points



}
@enduml
